version: '3'

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0.0
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      -  DBHOST=db
  mvc:
    image: front_opgave:1
    restart: always
    depends_on:
      - api
    environment:
      - BE_HOST=api
    ports:
      - 8080:8080




    

